# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mapterrain < Formula
  desc "Signal-first test intelligence CLI"
  homepage "https://github.com/pmclSF/terrain"
  version "0.1.0"
  license "Apache-2.0"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/pmclSF/terrain/releases/download/v0.1.0/terrain_0.1.0_linux_amd64.tar.gz"
    sha256 "3cb6ab1b15031683fdd338717410edff876eab3dad28b7c45b1da54513e60a91"
    define_method(:install) do
      bin.install "terrain"
    end
  end

  test do
    system "#{bin}/terrain", "version"
  end
end
