# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mapterrain < Formula
  desc "Signal-first test intelligence CLI"
  homepage "https://github.com/pmclSF/terrain"
  version "0.1.1"
  license "Apache-2.0"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/pmclSF/terrain/releases/download/v0.1.1/terrain_0.1.1_linux_amd64.tar.gz"
    sha256 "23ce16273a4557c3663493c5e0d9596a3a3a0bacdcee7b47f0d8d3b2b941ebf2"
    define_method(:install) do
      bin.install "terrain"
    end
  end

  test do
    system "#{bin}/terrain", "version"
  end
end
